### PR TITLE
Define JSON.lower(CatValue) if JSON is available

### LINKED ISSUE #95: JSON serialization of CategoricalValue{T, R} is broken
Now `CategoricalValue` is not a `<: AbstractString`, so JSON.jl serializes it using `CompositeTypeWrapper` and goes into recursion due to circular `pool` -> value -> `pool` references.

```
julia> using CategoricalArrays, JSON

julia> x = categorical([1, 2, 3]);

julia> JSON.json(x[1])
ERROR: StackOverflowError:
Stacktrace:
 [1] Type at /home/astukalov/.julia/v0.6/JSON/src/Writer.jl:18 [inlined]
 [2] lower(::CategoricalArrays.CategoricalPool{Int64,UInt32,CategoricalArrays.CategoricalValue{Int64,UInt32}}) at /home/astukalov/.julia/v0.6/JSON/src/Writer.jl:40
 [3] show_pair(::JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::Symbol, ::CategoricalArrays.CategoricalPool{Int64,UInt32,CategoricalArrays.CategoricalValue{Int64,UInt32}}) at /home/astukalov/.julia/v0.6/JSON/src/Writer.jl:236
 [4] show_json(::JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::JSON.Writer.CompositeTypeWrapper{CategoricalArrays.CategoricalValue{Int64,UInt32}}) at /home/astukalov/.julia/v0.6/JSON/src/Writer.jl:294
 [5] show_json(::JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::Array{CategoricalArrays.CategoricalValue{Int64,UInt32},1}) at /home/astukalov/.julia/v0.6/JSON/src/Writer.jl:302
 [6] show_json(::JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::JSON.Writer.CompositeTypeWrapper{CategoricalArrays.CategoricalPool{Int64,UInt32,CategoricalArrays.CategoricalValue{Int64,UInt32}}}) at /home/astukalov/.julia/v0.6/JSON/src/Writer.jl:294
 [7] show_pair(::JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::Symbol, ::CategoricalArrays.CategoricalPool{Int64,UInt32,CategoricalArrays.CategoricalValue{Int64,UInt32}}) at /home/astukalov/.julia/v0.6/JSON/src/Writer.jl:236
 [8] show_json(::JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::JSON.Writer.CompositeTypeWrapper{CategoricalArrays.CategoricalValue{Int64,UInt32}}) at /home/astukalov/.julia/v0.6/JSON/src/Writer.jl:294
 [9] show_json(::JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::Array{CategoricalArrays.CategoricalValue{Int64,UInt32},1}) at /home/astukalov/.julia/v0.6/JSON/src/Writer.jl:302
 [10] show_json(::JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::JSON.Writer.CompositeTypeWrapper{CategoricalArrays.CategoricalPool{Int64,UInt32,CategoricalArrays.CategoricalValue{Int64,UInt32}}}) at /home/astukalov/.julia/v0.6/JSON/src/Writer.jl:294
 [11] show_pair(::JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::Symbol, ::CategoricalArrays.CategoricalPool{Int64,UInt32,CategoricalArrays.CategoricalValue{Int64,UInt32}}) at /home/astukalov/.julia/v0.6/JSON/src/Writer.jl:236
 [12] show_json(::JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::JSON.Writer.CompositeTypeWrapper{CategoricalArrays.CategoricalValue{Int64,UInt32}}) at /home/astukalov/.julia/v0.6/JSON/src/Writer.jl:294
 [13] show_json(::JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::Array{CategoricalArrays.CategoricalValue{Int64,UInt32},1}) at /home/astukalov/.julia/v0.6/JSON/src/Writer.jl:302
 [14] show_json(::JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::JSON.Writer.CompositeTypeWrapper{CategoricalArrays.CategoricalPool{Int64,UInt32,CategoricalArrays.CategoricalValue{Int64,UInt32}}}) at /home/astukalov/.julia/v0.6/JSON/src/Writer.jl:294
 [15] show_pair(::JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::Symbol, ::CategoricalArrays.CategoricalPool{Int64,UInt32,CategoricalArrays.CategoricalValue{Int64,UInt32}}) at /home/astukalov/.julia/v0.6/JSON/src/Writer.jl:236
 [16] show_json(::JSON.Writer.CompactContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::JSON.Serializations.StandardSerialization, ::JSON.Writer.CompositeTypeWrapper{CategoricalArrays.CategoricalValue{Int64,UInt32}}) at /home/astukalov/.julia/v0.6/JSON/src/Writer.jl:294
```

It could be easily fixed by implementing `JSON.lower(x::CategoricalValue)` method, but that would require introducing `CategoricalArrays -> JSON` dependency.
The more generic fix would be to implement support for circular references in `JSON`, but that would still print `CategoricalValue` incorrectly (probably we just need to show the stored value, i.e. `get(x::CategoricalValue)`).

### PR DESCRIPTION
**Pull request by alyst**
Uses Requires.jl to define `JSON.json(::CatValue)` if JSON is present.

Fixes #95

### CODE REVIEW

**Comment by ararslan** [comment]
I'm very much against adding a dependency on Requires in general, but especially in a package so far down the stack.

**Comment by nalimilan** [comment]
Yes, I'd rather wait until we have optional dependencies (IIUC they should be supported in Julia 0.7).

**Comment by ararslan** [comment]
> IIUC they should be supported in Julia 0.7

??? As of when?

**Comment by alyst** [comment]
Is there a proper way to optionally define `JSON.lower()` in v0.6? If there's no, I think the issue is quite serious and potentially wide-spread to add JSON.jl to REQUIRE (it depends only on Compat).

`Requires.jl` was the first thing I found, but if its usage is discoraged, maybe @MikeInnes can add a note to README.md?

**Comment by ararslan** [comment]
The use of Requires isn't discouraged in general; some packages and ecosystems prefer to use it, but the JuliaStats and JuliaData packages avoid it. It's a matter of preference and consistency.

> Is there a proper way to optionally define JSON.lower() in v0.6?

No

**Comment by nalimilan** [comment]
> ??? As of when?

I mean, when it will be released. :-)

I guess we could add a dependency on JSON until then, but that's not great and that would create a precedent for other dependencies. Last time we added a dependency on a lightweight Juno package for DataFrames, we ended up reverting it, so... Do you have an actual need for this?

**Comment by alyst** [comment]
> Do you have an actual need for this?

Sometimes I'm just saving dataframes to json, but today I have stumbled over it while trying to draw a plot using PlotlyJS (`scatter(dataframe, x=:somecategoricalcolumn, ...)`).
So this issue may potentially appear in many unexpected contexts.

**Comment by alyst** [comment]
As an alternative, maybe something along these lines: `CategoricalValue` uses `Ref{CategoricalPool}` to refer to the pool, while `JSON.lower(x::Ref)` (defined in `JSON` itself) just prints the address of `x`.

**Comment by nalimilan** [comment]
That's clever, but that could slow down some essential operations, so that doesn't sound great.

**Comment by nalimilan** [comment]
Given that this makes PlotlyJS unusable with DataFrames with categorical columns, I guess we should add the dependency on JSON for now (without Requires).

BTW, special support for CategoricalArrays will be needed so that the ordering of levels is respected when plotting. See similar issues: https://github.com/plotly/plotly.js/issues/189, https://github.com/altair-viz/altair/issues/245 and https://github.com/vega/vega-lite/issues/2915.

**Comment by alyst** [comment]
JSON is a hard dependency now. CI failures seem unrelated

**Comment by nalimilan** [comment]
Now that Requires.jl is no longer a hack, I've used it to get rid of the dependency on JSON: https://github.com/JuliaData/CategoricalArrays.jl/pull/163.

**Comment by nalimilan** [comment]
Actually, it turns out that Requires imposes a significant penalty on load time, which people complain about (https://github.com/JuliaData/DataFrames.jl/issues/1764). On my machine, with Julia master, `using JSON` takes 0.05s, while `using Requires` takes 0.19s. So I wonder whether it wouldn't be better to use a hard dependency for now. (But it's still really annoying that we have to load JSON at all. Hopefully at some point it will be possible to define methods without loading a package.)

**Comment by ararslan** [comment]
Yeah, Requires may no longer be a hack, but it still isn't a great solution. I'm fine with a dependency on JSON, as it's a common package to have installed anyway.

**Comment by nalimilan** [comment]
OK, see https://github.com/JuliaData/CategoricalArrays.jl/pull/189.

**Pull request merged**
