### PR TITLE
Remove CategoricalString

### PR DESCRIPTION
**Pull request by nalimilan**
Deprecate it in favor of `CategoricalValue{String}`. Keep all deprecations and add new ones so that most functionality keeps working. The main breaking change which cannot be avoided is the inheritance from `AbstractString`.

Stop overloading `Base.tostr_sizehint` as it appears to trigger lots of recompilation
and it's just a small optimization (see https://github.com/JuliaLang/julia/pull/33757#discussion_r341886873).

### CODE REVIEW

**Comment by ablaom** [comment]
Could I suggest/request this PR be split in two, and the corresponding PR's split between releases?

1) Let `categorical(["a", "b"])` and similar constructors create an object whose eltype is now `CategoricalValue{String}` (currently, it is still `CategoricalString`)

2) In the following  patched release, add the depreciation warnings to use of `CategricalString`.

**Comment by nalimilan** [comment]
What would be the advantage of that? Each of these changes would be breaking, which only requires more work for dependent packages. Also, this PR should keep most things working thanks to the many deprecations: you can still write `CategoricalString` and it's automatically replaced with `CategoricalValue{String}`.

**Comment by ablaom** [comment]
Fair enough. It's just that in our case (MLJ) this PR does not appear to break anything. We just get the warnings.

**Comment by nalimilan** [comment]
Perfect, that's exactly the ideal case!

**Pull request merged**
