### PR TITLE
Fix Depreciation

### PR DESCRIPTION
**Pull request by Nosferican**

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks, but that's not correct without using Compat (and bumping the requirement to the version that introduced that feature). The fact that tests passed indicates that this function isn't actually tested.

**Comment by Nosferican** [comment]
Compat [23570](https://github.com/JuliaLang/julia/pull/23570). Going to leave the version here for later. Better wait until the function gets a test?

**Comment by nalimilan** [comment]
Better fix it even if we don't have a test, though adding a test would be even better.

**Comment by nalimilan** [comment]
You also need to add `using Compat` somewhere, e.g. to `src/CategoricalArrays.jl`.

**Comment by Nosferican** [comment]
I think the Require file had dropped Compat, but `src/CategoricalArrays.jl` still had it in line 14.

**Comment by nalimilan** [comment]
Thanks!

**Pull request merged**
