### PR TITLE
Fix specificity of convert methods

### PR DESCRIPTION
**Pull request by timholy**
Independent of https://github.com/JuliaLang/julia/pull/22398#issuecomment-309269831, this may be a good idea.

The method I deleted is redundant.

### CODE REVIEW

**Comment by tkelman** [comment]
Thanks Tim

**Comment by nalimilan** [comment]
Thanks! To be clear, there's a bug in Julia anyway, right?

The remaining crashes on Windows nightlies are scary...

**Comment by tkelman** [comment]
possibly oom killed on linux nightly too

**Comment by timholy** [comment]
I'd at least call it a gotcha---it shouldn't be necessary to specify `<:Integer` if that's built into the type.

**Pull request merged**
